name: breast_mri_3.7
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - conda=4.14.0
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.8.0
  - cryptography=37.0.4
  - idna=3.4
  - krb5=1.19.3
  - libarchive=3.5.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=7.83.1
  - libiconv=1.17
  - libmamba=0.25.0
  - libmambapy=0.25.0
  - libsolv=0.7.22
  - libssh2=1.10.0
  - libxml2=2.10.1
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - lzo=2.10
  - mamba=0.25.0
  - menuinst=1.4.19
  - openssl=1.1.1u
  - pip=22.3.1
  - pybind11-abi=4
  - pycosat=0.6.3
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.7.16
  - python_abi=3.7
  - reproc=14.2.3
  - reproc-cpp=14.2.3
  - requests=2.31.0
  - ruamel_yaml=0.15.80
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.41.2
  - toolz=0.12.0
  - urllib3=2.0.3
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wxpython=4.0.4
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - zstandard=0.18.0
  - zstd=1.5.2
  - pip:
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - args==0.1.0
    - attrs==23.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - bleach==6.0.0
    - clint==0.5.1
    - cloudpickle==2.2.1
    - colorama==0.4.6
    - colorcet==3.0.1
    - comm==0.1.3
    - coverage==7.2.7
    - cycler==0.11.0
    - dask==2022.2.0
    - dcmstack==0.9.0
    - debugpy==1.6.7
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dicom==0.9.9.post1
    - dicom-numpy==0.6.5
    - dicom2nifti==2.4.8
    - dill==0.3.7
    - docopt==0.6.2
    - entrypoints==0.4
    - et-xmlfile==1.1.0
    - fastjsonschema==2.18.0
    - fonttools==4.38.0
    - fsspec==2023.1.0
    - glcontext==2.3.7
    - imageio==2.31.1
    - importlib-metadata==6.7.0
    - ipydatawidgets==4.3.2
    - ipykernel==6.16.2
    - ipympl==0.9.3
    - ipython==7.34.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.8.0
    - itk-core==5.3.0
    - itk-filtering==5.3.0
    - itk-meshtopolydata==0.10.0
    - itk-numerics==5.3.0
    - itkwidgets==0.32.6
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.3.1
    - jsonschema==3.2.0
    - jupyter-client==7.4.9
    - jupyter-core==4.12.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.5
    - kiwisolver==1.4.4
    - locket==1.0.0
    - lxml==4.9.3
    - markupsafe==2.1.3
    - matplotlib==3.5.3
    - matplotlib-inline==0.1.6
    - mistune==3.0.1
    - moderngl==5.8.2
    - multipledispatch==0.6.0
    - nbclient==0.7.4
    - nbconvert==7.6.0
    - nbformat==5.8.0
    - nest-asyncio==1.5.6
    - networkx==2.6.3
    - nibabel==4.0.2
    - nilearn==0.10.1
    - notebook==6.4.12
    - nptyping==2.5.0
    - numpy==1.21.5
    - openpyxl==3.1.2
    - packaging==23.1
    - pandarallel==1.6.5
    - pandas==1.3.5
    - pandocfilters==1.5.0
    - param==1.13.0
    - parso==0.8.3
    - partd==1.4.1
    - pickleshare==0.7.5
    - pillow==9.5.0
    - plotly==5.15.0
    - plyfile==0.9
    - prometheus-client==0.17.1
    - prompt-toolkit==3.0.38
    - psutil==5.9.5
    - pyct==0.5.0
    - pydicom==2.4.1
    - pydicom-seg==0.4.1
    - pygments==2.15.1
    - pykwalify==1.8.0
    - pylibjpeg-libjpeg==1.3.4
    - pynrrd==1.0.0
    - pyparsing==3.1.0
    - pyradiomics==3.1.0
    - pyrr==0.10.3
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-gdcm==3.0.22
    - pytz==2023.3
    - pywavelets==1.3.0
    - pywin32==306
    - pywinpty==2.0.10
    - pyyaml==6.0.1
    - pyzmq==25.1.0
    - ruamel-yaml==0.17.32
    - ruamel-yaml-clib==0.2.7
    - scikit-fuzzy==0.4.2
    - scikit-image==0.19.3
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.12.2
    - send2trash==1.8.2
    - simple-3dviz==0.7.0
    - simpleitk==2.2.1
    - soupsieve==2.4.1
    - swifter==1.4.0
    - tenacity==8.2.2
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tifffile==2021.11.2
    - tinycss2==1.2.1
    - tornado==6.2
    - tqdm==4.65.0
    - traitlets==5.6.0
    - traittypes==0.2.1
    - trimesh==3.22.4
    - typing-extensions==4.6.3
    - wcwidth==0.2.6
    - webencodings==0.5.1
    - widgetsnbextension==3.6.5
    - zipp==3.15.0