wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: 3D ConvNet
epochs:
  desc: null
  value: 25
batch_size:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.10
    framework: huggingface
    huggingface_version: 4.33.1
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1699688613.816545
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      3:
      - 2
      - 3
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.15.10
      6: 4.33.1
      8:
      - 1
      - 2
      - 3
      - 5
