wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
architecture:
  desc: null
  value: 3D ConvNet
epochs:
  desc: null
  value: 30
batch_size:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.35.0
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1699352684.816848
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.0
      5: 0.15.12
      6: 4.35.0
      8:
      - 1
      - 2
      - 3
      - 5
      13: windows-amd64
